blank_issues_enabled: false
contact_links:
  - name: Binhex Minecraft Bedrock support
    url: https://forums.unraid.net/topic/84905-support-binhex-minecraftbedrockserver/
    about: Use this for issues with the Minecraft server container itself rather than CraftCommand Center.
